version: '3'

services:

# Nginx
  nginx:
    image: nginx
    build:
      context: ../../
      dockerfile: requirements/nginx/Dockerfile
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - ../nginx/conf/:/etc/nginx/http.d/
      - ../nginx/tools:/etc/nginx/ssl/
      - wp-volume:/var/www/
    restart: always


# MariaDB
  mariadb:
    image: mariadb
    build:
      context: ../../
      dockerfile: requirements/mariadb/Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
        DB_ROOT: ${DB_ROOT}
    container_name: mariadb
    ports:
      - "3306:3306"
    networks:
      - inception
    volumes:
      - db-volume:/var/lib/mysql
    restart: always

# Wordpress
  wordpress:
    image: wordpress
    build:
      context: ../../
      dockerfile: requirements/wordpress/Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
        WP_USER: ${WP_USER}
        WP_PASS: ${WP_PASS}
        WP_ADDR: ${WP_ADDR}
    container_name: wordpress
    depends_on:
      - mariadb
    restart: always
    networks:
      - inception
    volumes:
      - wp-volume:/var/www/

# Bonus - Redis
  redis:
    image: redis
    build:
      context: ../../
      dockerfile: requirements/bonus/requirements/redis/Dockerfile
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - inception
    restart: always

#Bonus - VSFTP
  vsftpd:
    image: vsftp
    build:
      context: ../../
      dockerfile: requirements/bonus/requirements/vsftpd/Dockerfile
      args:
        FTP_USR: ${FTP_USR}
        FTP_PWD: ${FTP_PWD}
    container_name: vsftpd
    ports:
      - "21:21"
    volumes:
      - wp-volume:/var/www/
    networks:
     - inception
    restart: always

#Bonus - Adminer
  adminer:
    image: adminer
    build:
      context: ../../
      dockerfile: requirements/bonus/requirements/adminer/Dockerfile
    container_name: adminer
    depends_on:
      - mariadb
    ports:
      - "8080:8080"
    networks:
     - inception
    restart: always

#Bonus - Website
  website:
    image: website
    build:
      context: ../../
      dockerfile: requirements/bonus/requirements/website/Dockerfile
    container_name: website
    ports:
      - "80:80"
    restart: always

#Bonus - Portainer
  portainer:
    image: portainer
    build:
      context: ../../
      dockerfile: requirements/bonus/requirements/portainer/Dockerfile
    container_name: portainer
    ports:
      - "9443:9443"
    networks:
      - inception
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: always


volumes:
  wp-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/wordpress

  db-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/mariadb

  portainer_data:

networks:
    inception:
        driver: bridge
